In [1]:
!pip install xgboost

Requirement already satisfied: xgboost in /Users/julissaguzman/opt/anaconda3/lib/python3.8/site-packages (1.3.3)
Requirement already satisfied: numpy in /Users/julissaguzman/opt/anaconda3/lib/python3.8/site-packages (from xgboost) (1.18.5)
Requirement already satisfied: scipy in /Users/julissaguzman/opt/anaconda3/lib/python3.8/site-packages (from xgboost) (1.5.0)

In [1]:
from numpy import loadtxt
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
#open csv as df
currentpoints = pd.read_csv('api/data/resources/currentpoints.csv')
currentpoints_df = pd.DataFrame(currentpoints)
currentpoints_df

,id,second_name,first_name,value_season,value_form,form,total_points,points_per_game,team,team_code,...,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,position
0,302,Borges Fernandes,Bruno Miguel,12.5,0.4,4.7,142,7.1,Man Utd,1,...,4,0,0,22,514,776.0,859.9,710.0,234.8,MID
1,388,Kane,Harry,12.6,0.6,7.2,142,7.9,Spurs,6,...,1,0,0,26,513,763.4,371.1,790.0,192.4,FWD
2,390,Son,Heung-Min,14.3,0.5,5.0,139,7.7,Spurs,6,...,0,0,0,18,436,639.2,494.7,598.0,173.5,MID
3,254,Salah,Mohamed,10.3,0.1,1.8,129,7.2,Liverpool,14,...,0,0,0,13,383,616.8,441.0,896.0,195.3,MID
4,224,Vardy,Jamie,11.6,0.2,2.2,116,6.4,Leicester,13,...,1,0,0,17,412,527.8,183.3,762.0,147.4,FWD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,199,Forshaw,Adam,0.0,0.0,0.0,0,0.0,Leeds,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,MID
640,196,Douglas,Barry,0.0,0.0,0.0,0,0.0,Leeds,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,DEF
641,237,Benkovic,Filip,0.0,0.0,0.0,0,0.0,Leicester,13,...,0,0,0,0,0,0.0,0.0,0.0,0.0,DEF
642,1,Ã–zil,Mesut,0.0,0.0,0.0,0,0.0,Arsenal,3,...,0,0,0,0,0,0.0,0.0,0.0,0.0,MID
643,31,Taylor,Neil,-0.2,0.0,-0.2,-1,-1.0,Aston Villa,7,...,1,0,0,0,1,0.8,0.7,0.0,0.2,DEF

In [3]:
#drop non-numeric columns
currentpoints_df_num = currentpoints_df.drop(['second_name','first_name','team','in_dreamteam','position'],axis = 1)
currentpoints_df_num

,id,value_season,value_form,form,total_points,points_per_game,team_code,now_cost,event_points,chance_of_playing_next_round,...,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index
0,302,12.5,0.4,4.7,142,7.1,1,114,2,NaN,...,1,4,0,0,22,514,776.0,859.9,710.0,234.8
1,388,12.6,0.6,7.2,142,7.9,6,113,0,100.0,...,0,1,0,0,26,513,763.4,371.1,790.0,192.4
2,390,14.3,0.5,5.0,139,7.7,6,97,0,100.0,...,0,0,0,0,18,436,639.2,494.7,598.0,173.5
3,254,10.3,0.1,1.8,129,7.2,14,125,0,100.0,...,0,0,0,0,13,383,616.8,441.0,896.0,195.3
4,224,11.6,0.2,2.2,116,6.4,13,100,0,0.0,...,1,1,0,0,17,412,527.8,183.3,762.0,147.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,199,0.0,0.0,0.0,0,0.0,2,48,0,0.0,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
640,196,0.0,0.0,0.0,0,0.0,2,38,0,0.0,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
641,237,0.0,0.0,0.0,0,0.0,13,43,0,0.0,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
642,1,0.0,0.0,0.0,0,0.0,3,67,0,0.0,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
643,31,-0.2,0.0,-0.2,-1,-1.0,7,42,0,NaN,...,0,1,0,0,0,1,0.8,0.7,0.0,0.2

In [4]:
#convert df to floats

currentpoints_df_num = currentpoints_df_num.astype(float)
#drop na values
currentpoints_df_final = currentpoints_df_num.fillna(0)

In [6]:
#save floats as new csv file
currentpoints_df.to_csv('api/data/resources/currentpoints_floats.csv', index=False)
currentpoints_df_final.to_csv('api/data/resources/currentpoints_final.csv', index=False)

In [8]:
data = loadtxt('api/data/resources/currentpoints_final.csv', delimiter=',', skiprows = 1)
data

array([[ 3.020e+02,  1.250e+01,  4.000e-01, ...,  8.599e+02,  7.100e+02,
         2.348e+02],
       [ 3.880e+02,  1.260e+01,  6.000e-01, ...,  3.711e+02,  7.900e+02,
         1.924e+02],
       [ 3.900e+02,  1.430e+01,  5.000e-01, ...,  4.947e+02,  5.980e+02,
         1.735e+02],
       ...,
       [ 2.370e+02,  0.000e+00,  0.000e+00, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [ 1.000e+00,  0.000e+00,  0.000e+00, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [ 3.100e+01, -2.000e-01,  0.000e+00, ...,  7.000e-01,  0.000e+00,
         2.000e-01]])